# SPDX-FileCopyrightText: 2024 Sefa Eyeoglu <contact@scrumplex.net>
#
# SPDX-License-Identifier: CC0-1.0

[monado]
src.git = "https://gitlab.freedesktop.org/monado/monado.git"
fetch.git = "https://gitlab.freedesktop.org/monado/monado.git"

[opencomposite]
src.git = "https://gitlab.com/znixian/OpenOVR.git"
fetch.git = "https://gitlab.com/znixian/OpenOVR.git"
git.fetchSubmodules = true

[opencomposite-hand-fixes]
src.git = "https://gitlab.com/znixian/OpenOVR.git"
src.branch = "hand-fixes"
fetch.git = "https://gitlab.com/znixian/OpenOVR.git"
git.fetchSubmodules = true

[index_camera_passthrough]
src.git = "https://github.com/yshui/index_camera_passthrough.git"
fetch.git = "https://github.com/yshui/index_camera_passthrough.git"
cargo_locks = ["Cargo.lock"]

[wlx-overlay-s]
src.git = "https://github.com/galister/wlx-overlay-s.git"
fetch.git = "https://github.com/galister/wlx-overlay-s.git"
cargo_locks = ["Cargo.lock"]
