# SPDX-FileCopyrightText: 2024 Sefa Eyeoglu <contact@scrumplex.net>
# SPDX-FileCopyrightText: 2025 Aki <Aki@ToasterUwU.com>
#
# SPDX-License-Identifier: CC0-1.0

[eepyxr]
fetch.git = "https://github.com/Beyley/eepyxr.git"
src.git = "https://github.com/Beyley/eepyxr.git"

[envision-unwrapped]
cargo_locks = ["Cargo.lock"]
fetch.git = "https://gitlab.com/gabmus/envision.git"
src.git = "https://gitlab.com/gabmus/envision.git"

[index_camera_passthrough]
cargo_locks = ["Cargo.lock"]
fetch.git = "https://github.com/yshui/index_camera_passthrough.git"
src.git = "https://github.com/yshui/index_camera_passthrough.git"

[monado]
fetch.git = "https://gitlab.freedesktop.org/monado/monado.git"
src.git = "https://gitlab.freedesktop.org/monado/monado.git"

[opencomposite]
fetch.git = "https://gitlab.com/znixian/OpenOVR.git"
git.fetchSubmodules = true
src.git = "https://gitlab.com/znixian/OpenOVR.git"

[wayvr-dashboard]
cargo_locks = ["src-tauri/Cargo.lock"]
fetch.git = "https://github.com/olekolek1000/wayvr-dashboard"
src.git = "https://github.com/olekolek1000/wayvr-dashboard"

[wivrn]
fetch.github = "WiVRn/WiVRn"
src.git = "https://github.com/WiVRn/WiVRn"

[wivrn-monado]
fetch.git = "https://gitlab.freedesktop.org/monado/monado.git"
src.webpage = "https://github.com/WiVRn/WiVRn/raw/refs/heads/master/monado-rev"
src.regex = "(\\w+)"

[wlx-overlay-s]
cargo_locks = ["Cargo.lock"]
fetch.git = "https://github.com/galister/wlx-overlay-s.git"
src.git = "https://github.com/galister/wlx-overlay-s.git"

[xrizer]
cargo_locks = ["Cargo.lock"]
fetch.git = "https://github.com/Supreeeme/xrizer.git"
src.git = "https://github.com/Supreeeme/xrizer.git"
